- name: Update license statement in make.conf
  lineinfile:
    path: /mnt/gentoo/etc/portage/make.conf
    regex: '^\s*ACCEPT_LICENSE'
    state: present
    line: 'ACCEPT_LICENSE="* -@EULA"'

- name: create repos parent
  command: mkdir --parents /mnt/gentoo/etc/portage/repos.conf
  args:
    creates: /mnt/gentoo/etc/portage/repos.conf/gentoo.conf    

- name: set repos
  command: cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
  args:
    creates: /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

- name: eselect profile
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile set {{ eselect_profile }}'
  tags:
    - chroot

- name: Emerge Gentoo Sources
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge gentoo-sources' creates=/mnt/gentoo/usr/src/linux/arch
  tags:
    - kernel

- name: TODO symlink the latest kernel to /usr/src/linux
  command: ln -s usr/src/linux-5.10.76-gentoo-r1 usr/src/linux
  args:
    creates: usr/src/linux
    chdir: /mnt/gentoo/

- name: Install Genkernel
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge genkernel' creates=/mnt/gentoo/usr/bin/genkernel
  
- name: Run genkernel
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; genkernel all'

- name: Install Initramfs
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; genkernel --lvm --install initramfs'
