- name: Create networkingd file
  copy:
    src: 50-dhcp.network
    dest: /mnt/gentoo/etc/systemd/network/50-dhcp.network
    

- name: enable network service
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; systemctl enable systemd-networkd.service'

- name: enable network service
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; systemctl enable systemd-networkd.service'

- name: Create root .ssh Directory
  command: mkdir -p /mnt/gentoo/root/.ssh && chmod 700 /mnt/gentoo/root/.ssh && chmod 600 /mnt/gentoo/root/.ssh

- name: Configure Root Authorized Key
  authorized_key: user=root
                  key="{{ lookup('file', pubkey) }}"
                  path="/mnt/gentoo/root/.ssh/authorized_keys"
